### ISSUE TITLE
Escaping for lparen, rparen, and pipe needed.

### ISSUE THREAD

**Issue by jcjimenez** [CatalystCode/streaming-bing#4]
In the unlikely event that a search keyword contains a character used for building a multi-term logical OR expression, it's possible a incorrect query parameter. For instance, if the user [mistakenly] entered these two terms (note the unbalanced lparen in the second keyword):

```
foo
bar (1
```
the query parameter sent to Bing would look something like this unbalanced expression:

```
q=(foo)||(bar%20(1)
```
A simple solution would be to make sure that these characters are escaped in the same way spaces are replaced with `%20`.

**Comment by c-w** [comment]
Implementation will need to touch the encoding code in [loadBingPostings](https://github.com/CatalystCode/streaming-bing/blob/d1fdc2f4d5f69b052434c25429cc7ddc233eab38/src/main/scala/com/github/catalystcode/fortis/spark/streaming/bing/client/BingClient.scala#L46).

**Comment by c-w** [comment]
I have a patch for this.
